name: Flutter CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.COMMIT_SECRET }}

      - name: Repository
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo "::set-output name=repository::$REPOSITORY"
      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.5'
          channel: 'stable'
          cache: 'true'

      - run: flutter --version
      - run: flutter upgrade 

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --web-renderer html --base-href /${{ steps.version.outputs.repository }}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.COMMIT_SECRET }}
          publish_dir: ./build/web
